version: "3.8"
services:
  php-apache-environment:
    container_name: Monkai_web
    build:
      context: ./public
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html/
    command: >
      bash -c "a2enmod rewrite && apache2-foreground"
    ports:
      - 8000:80
  